### ISSUE TITLE
Sample Files for Countess™ 3 and 3 FL cell counters

### ISSUE THREAD

**Issue by pooja-b05** [VincenzoCardaci/Countess3FL_JSON_analizer#1]
Your code provided valuable insights for cell counter analysis. It would be better if you could provide the test files/sample files that you have used to test the code.

I also noticed that the cell counter produces CSV files and not JSON. I'm interested to know how you obtained JSON exports from the cell counter software.

![image](https://github.com/user-attachments/assets/679b89a5-e09a-4208-82dd-d2244c1f2dfc)

**Comment by VincenzoCardaci** [comment]
Thank you pooja-b05 for your feedback! I appreciate your interest.
Regarding your request, I have uploaded two sample files (for fluorescent or only brightness count) that I used to test the code. You can find it in the repository.
As for the JSON exports, the cell counter software automatically generates JSON files as part of the save operation. If you look into the save directory, you should see the JSON files alongside the CSV files.

Please let me know if you need any further assistance.
